<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>f7fad539-ec69-4101-903b-88574b228acd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductManagement.Api\ProductManagement.Api.csproj" />
    <ProjectReference Include="..\ProductManagement.MigrationService\ProductManagement.MigrationService.csproj" />
  </ItemGroup>

</Project>
